export const DEFAULT_CYCLE = {
    year: 2026,
    label: "KVW 2026",
    status: "open" as const,
    isTestMode: true,
    childRegistrationsOpen: true,
    volunteerRegistrationsOpen: true,
    childRegistrationsOpenAt: new Date("2026-05-15T12:00:00.000Z"),
    childRegistrationsCloseAt: new Date("2026-06-15T12:00:00.000Z"),
    volunteerRegistrationsOpenAt: new Date("2026-05-15T12:00:00.000Z"),
    volunteerRegistrationsCloseAt: new Date("2026-06-15T12:00:00.000Z"),
    pricePerChild: "38.00",
    maxChildrenPerRegistration: 1,
    maxGuardiansPerRegistration: 1,
};

export const DEFAULT_PAGES = [
    {
        slug: "home",
        title: "Homepagina",
        summary: "Welkomsttekst en basisinformatie",
        body: "Al ruim 55 jaar organiseert HeKoS Kindervakantiewerk elk jaar een leuke week vol activiteiten voor kinderen van de basisschool! Jaarlijks 5 dagen vol plezier in de laatste week van de zomervakantie.",
        isPublished: true,
    },
    {
        slug: "over-ons",
        title: "Over ons",
        summary: "KVW HeKoS organiseert al ruim 55 jaar een gezellige en actieve vakantieweek voor kinderen in Tilburg.",
        body: [
            "KVW HeKoS organiseert al ruim 55 jaar een gezellige en actieve vakantieweek voor kinderen in Tilburg. Ons doel is simpel: kinderen een veilige, betaalbare en onvergetelijke week bezorgen.",
            "Onze missie is om een plek te bieden waar kinderen zichzelf kunnen zijn, nieuwe vrienden maken en met plezier terugdenken aan hun zomervakantie. We geloven dat laagdrempelige activiteiten een groot verschil kunnen maken.",
            "Daarom letten we niet alleen op leuke programma-onderdelen, maar ook op sfeer, veiligheid en persoonlijke aandacht. Iedere groep krijgt begeleiding van enthousiaste vrijwilligers die oog hebben voor wat kinderen nodig hebben.",
            "Samen met ouders, sponsoren en vrijwilligers zorgen we voor een week die voelt als een feestje, en tegelijk bijdraagt aan zelfvertrouwen, samenwerking en plezier.",
        ].join("\n\n"),
        isPublished: true,
    },
    {
        slug: "gedragscode",
        title: "Gedragscode",
        summary: "Afspraken voor een veilige week",
        body: [
            "We behandelen kinderen, ouders, vrijwilligers en elkaar met respect. We zorgen voor een veilige, inclusieve en positieve sfeer tijdens alle activiteiten.",
            "Veiligheid staat voorop. We zorgen samen voor een omgeving waarin kinderen zich fysiek en sociaal veilig voelen, met duidelijke grenzen en actieve begeleiding.",
            "Respect in gedrag en taal. Iedereen gaat op een respectvolle manier met elkaar om. We spreken elkaar normaal aan en luisteren naar elkaar, ook als we het oneens zijn.",
            "Samen verantwoordelijk. Vrijwilligers, ouders en deelnemers dragen samen bij aan een fijne sfeer. We grijpen in wanneer dat nodig is en laten elkaar niet zwemmen.",
            "Gedrag dat niet past bij HeKoS: pesten, uitsluiten of intimideren; discriminatie; fysiek of verbaal grensoverschrijdend gedrag; bewust negeren van veiligheidsinstructies; en het delen van beeldmateriaal zonder toestemming van ouder of verzorger.",
            "Zie of hoor je iets dat niet klopt? Meld het direct bij een hoofdleider of vertrouwenspersoon. We luisteren zonder oordeel en nemen maatregelen die passen bij de situatie.",
        ].join("\n\n"),
        isPublished: true,
    },
    {
        slug: "sponsorpakketten",
        title: "Sponsorpakketten",
        summary: "Met jouw bijdrage houden we KVW HeKoS betaalbaar en toegankelijk voor alle kinderen.",
        body: [
            "Met jouw bijdrage houden we KVW HeKoS betaalbaar en toegankelijk voor alle kinderen. Stuur ons een bericht en we denken graag mee over een passend pakket.",
            "Basis (EUR 250): logo op de website, vermelding op het sponsorbord en een bedankje op social media.",
            "Groei (EUR 500, meest gekozen): alles uit Basis, extra zichtbaarheid tijdens de week en vermelding in het programmaboekje.",
            "Hoofdsponsor (EUR 1000+): alles uit Groei, hoofdsponsor-vermelding op alle uitingen en een maatwerkactivatie in overleg.",
        ].join("\n\n"),
        isPublished: true,
    },
    {
        slug: "bevestiging-kind",
        title: "Bevestiging kind",
        summary: "Tekst na kindinschrijving",
        body: "Bedankt voor de inschrijving(en) van uw kind(eren). Op naar weer een prachtige editie van KVW! Binnenkort ontvangt u meer informatie van ons over KVW zoals het programma. We nemen hierover contact met u op per mail. Heeft u voor nu dringende vragen, neem dan contact met ons op via info@kvwhekos.nl.",
        isPublished: true,
    },
    {
        slug: "bevestiging-vrijwilliger",
        title: "Bevestiging vrijwilliger",
        summary: "Tekst na vrijwilligersaanmelding",
        body: "Bedankt voor je aanmelding als vrijwilliger. We nemen zo snel mogelijk contact met je op per mail. Voor dringende vragen kun je terecht via info@kvwhekos.nl.",
        isPublished: true,
    },
];

export const DEFAULT_BLOCKS = [
    {
        pageSlug: "home",
        blockKey: "hero.eyebrow",
        title: "Homepagina eyebrow",
        body: "welkom bij HeKoS Kindervakantiewerk",
        sortOrder: 1,
        isActive: true,
    },
    {
        pageSlug: "home",
        blockKey: "hero.title",
        title: "Homepagina titel",
        body: "De leukste vakantie activiteit voor kinderen!",
        sortOrder: 2,
        isActive: true,
    },
    {
        pageSlug: "home",
        blockKey: "hero.intro",
        title: "Homepagina intro",
        body: "Al ruim 55 jaar organiseert HeKoS Kindervakantiewerk elk jaar een leuke week vol activiteiten voor kinderen van de basisschool! Jaarlijks 5 dagen vol plezier in de laatste week van de zomervakantie.",
        sortOrder: 3,
        isActive: true,
    },
    {
        pageSlug: "home",
        blockKey: "programma.updatedAt",
        title: "Programma laatst bijgewerkt",
        body: "1 juni 2026",
        sortOrder: 4,
        isActive: true,
    },
    {
        pageSlug: "home",
        blockKey: "groepen.updatedAt",
        title: "Groepenlijst laatst bijgewerkt",
        body: "1 juni 2026",
        sortOrder: 5,
        isActive: true,
    },
];

export const DEFAULT_SPONSORS = [
    {
        name: "CBWD",
        websiteUrl: "https://cbwd.dev",
        logoUrl: "/cbwd.webp",
        placement: "both" as const,
        sortOrder: 1,
        isActive: true,
    },
    {
        name: "ServerPunt",
        websiteUrl: "https://serverpunt.com",
        logoUrl: "/serverpunt.webp",
        placement: "both" as const,
        sortOrder: 2,
        isActive: true,
    },
    {
        name: "Blossem",
        websiteUrl: null,
        logoUrl: "/blossem.png",
        placement: "both" as const,
        sortOrder: 3,
        isActive: true,
    },
    {
        name: "GH Events",
        websiteUrl: null,
        logoUrl: "/ghevents.png",
        placement: "both" as const,
        sortOrder: 4,
        isActive: true,
    },
    {
        name: "Gianotten Mutsaers",
        websiteUrl: null,
        logoUrl: "/GianottenMutsaers.jpg",
        placement: "both" as const,
        sortOrder: 5,
        isActive: true,
    },
    {
        name: "KAV A Vlam",
        websiteUrl: null,
        logoUrl: "/logokavavlam.png",
        placement: "both" as const,
        sortOrder: 6,
        isActive: true,
    },
    {
        name: "Zomerlust",
        websiteUrl: null,
        logoUrl: "/zomerlust.png",
        placement: "both" as const,
        sortOrder: 7,
        isActive: true,
    },
];

export const DEFAULT_DOCUMENTS = [
    {
        kind: "program" as const,
        title: "Programma",
        description: "Het KVW-programma van dit jaar",
        fileUrl: "/programma.pdf",
        opensInNewTab: true,
        isActive: true,
    },
    {
        kind: "group_assignment" as const,
        title: "Groepsindeling",
        description: "De groepenlijst van dit jaar",
        fileUrl: "/groepen.pdf",
        opensInNewTab: true,
        isActive: true,
    },
];
